### PR TITLE
Fixes a problem with php 7.4

### PR DESCRIPTION
**Pull request by LinkingYou**
This would fix the issue #75

### CODE REVIEW

**Comment by carlospauluk** [comment]
Please, merge!

**Comment by eduardoturconi** [comment]
Why is it taking so long to merge?

**Comment by MatthiasKuehneEllerhold** [comment]
Please merge and release... !

**Comment by poldixd** [comment]
Hm, the last commit of this package is almost two years ago :-(

**Comment by marijnbent** [comment]
I think someone needs to fork this

**Comment by carlospauluk** [comment]
> I think someone needs to fork this

Totally agree!

**Comment by carlospauluk** [comment]
Please see: https://github.com/dompdf/dompdf/issues/2063

**Comment by andrefedalto** [comment]
I'm using dompdf through laravel and having the same issue. One workaround I could find is:
1. Apply the fix by @LinkingYou locally on `vendor\phenx\php-font-lib\src\FontLib\AdobeFontMetrics.php:142`;
1. Set your font folder for dompdf to a folder in your repository;
1. Run your script to build the pdf locally, this will make dompdf generate all font temp files (ttf, ufm, php) in your font folder;
1. Commit these files to your repository;
1. 🎉 dompdf will now use the parsed fonts instead of parsing them again. Remember you have to repeat all the steps here for each new font you use

**Comment by jeliasson** [comment]
@PhenX Can you kindly release `master` to `0.5.2`? This will allow us to have it fixed in e.g. `dompdf/dompdf`.

**Comment by enumag** [comment]
@jeliasson There are more things wrong with 7.4, see https://github.com/PhenX/php-font-lib/pull/77. Also it would be good to have 7.4 compatibility verified on travis, see https://github.com/PhenX/php-font-lib/pull/74. In my opinion it makes no sense to make a release until these are merged.

**Comment by jeliasson** [comment]
@enumag It would surely be nice to have all 7.4 issues fixed in the same release, but considering there are downstream packages that seems to benefit from this merge alone I think it would not hurt to throw in a minor release. Anyway, let's hope for a few merges and a release bump soon.

**Comment by sandervanhooft** [comment]
+1 for a hot fix (minor release); many integrations are (partially) broken by this issue.

That being said, I don't have the full picture of what's involved (or anyone's time schedule).

**Comment by manogi** [comment]
What @sandervanhooft said. I also would like to kindly ask for a commit just addressing this one issue, if in any way possible.

**Comment by jeliasson** [comment]
Following up on what @LinkingYou suggested, here is a donkey-patch based off @andrefedalto's contribution (31cad9151aa2a7070e73bc53dc2d104fdce7e0c6).

```bash
# Donkey patch vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php
cat vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php | sed "s/\$tree\W\=\W\$kern\[\"tree\"\]\;/\$tree \= is_array\(\$kern\) \? \$kern\[\"tree\"\]\ : null\;/g"

# Verify output of donkey patch
cat vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php | grep '$tree = '
```

Hope it helps someone!

**Comment by dj3plles** [comment]
This helps @jeliasson

**Comment by ManWuzi** [comment]
@jeliasson Thanks a lot! This really helped

**Comment by ngunyimacharia** [comment]
Really hope this is permanently closed soon.

**Comment by PhenX** [comment]
Hello, 0.5.2 already has this fix, nothing was pushed to master since its release. What can I do more ?

**Comment by ngunyimacharia** [comment]
Had not noticed, left this thread before it was pushed. Thank you

**Pull request merged**
